### ISSUE TITLE
How do you deploy this to a live site?

### ISSUE THREAD

**Issue by tonychandesign** [symblai/symbl-twilio-video-react#6]
Hello, i'd like to create a prototype and test this for mobile.  I'm trying to deploy it using twilio, using the instructions from https://github.com/twilio/twilio-video-app-react.

Unfortunately i get a bank page and nothing really shows up.  https://video-app-2930-2706-dev.twil.io/?passcode=38791129302706

**Comment by eric-giannini** [comment]
@tonychandesign May you please send an email to support@symbl.ai?

**Comment by eric-giannini** [comment]
@tonychandesign @HuckMatt let me know that he resolved your opened ticket! May you please confirm?

**Comment by eric-giannini** [comment]
@tonychandesign @HuckMatt let me know that he was able to deploy a website to Heroku! Thanks, @tonychandesign.
